// Russian item-name overlay for search. Keyed by the stable Rust shortName
// (validated to exist in items.js ITEMS); the first string is the canonical RU
// name, the rest are slang/synonyms players actually type. items.js folds these
// into its REVERSE map (English stays authoritative on collisions) so
// resolveItemId() matches Russian queries with no change to its contract.
//
// Slang sourced from community glossaries + the owner's crew. Covers items that
// actually trade in vending machines. To extend: add a `shortName: [ru, …]` line.
export const RU_ALIASES = {
  // — Взрывчатка / рейд —
  'explosive.timed': ['с4', 'c4', 'си4', 'сишка', 'таймер'],
  explosives: ['взрывчатка', 'вз'],
  'ammo.rocket.basic': ['ракета', 'ракеты', 'рокет'],
  'ammo.rocket.hv': ['скоростная ракета', 'hv ракета', 'хв ракета'],
  'ammo.rocket.fire': ['зажигательная ракета', 'огненная ракета'],
  'ammo.rocket.smoke': ['дымовая ракета'],
  'ammo.rocket.mlrs': ['ракета mlrs', 'млрс'],
  'explosive.satchel': ['сачель', 'сачелька', 'сачели', 'сачельки', 'сач', 'сачел', 'satchel', 'связка'],
  'grenade.beancan': ['бинкан', 'бинка', 'бобовка', 'бобовая граната', 'beancan'],
  'grenade.f1': ['ф1', 'граната ф1', 'f1', 'граната'],
  'grenade.flashbang': ['флешка', 'светошумовая', 'flashbang'],
  'grenade.molotov': ['молотов', 'коктейль', 'молик'],
  gunpowder: ['порох'],
  'ammo.rifle.explosive': ['разрывной патрон', 'разрывные', 'рпатрон'],
  surveycharge: ['заряд разведки', 'сюрвей', 'разведочный заряд'],
  'supply.signal': ['сопля', 'сигналка', 'сигнал', 'дымовая шашка вызова'],
  // — Патроны —
  'ammo.rifle': ['патрон 5.56', 'патроны автоматные', '5.56', 'винтовочные патроны', 'автоматный патрон', 'патроны'],
  'ammo.rifle.hv': ['скоростной патрон', 'hv патрон'],
  'ammo.rifle.incendiary': ['зажигательный патрон', 'incendiary'],
  'ammo.pistol': ['пистолетный патрон', 'пистолетные патроны'],
  'ammo.pistol.hv': ['скоростной пистолетный'],
  'ammo.pistol.fire': ['зажигательный пистолетный'],
  'ammo.shotgun': ['картечь', 'дробь', 'патрон дробовик'],
  'ammo.shotgun.slug': ['пуля', 'слаг', 'slug'],
  'ammo.shotgun.fire': ['зажигательная дробь'],
  'ammo.handmade.shell': ['самодельные патроны', 'самопал патрон', 'хендмейд', 'handmade'],
  'arrow.wooden': ['стрела', 'деревянная стрела', 'стрелы'],
  'arrow.hv': ['скоростная стрела'],
  'arrow.fire': ['зажигательная стрела', 'огненная стрела'],
  'arrow.bone': ['костяная стрела'],
  'ammo.nailgun.nails': ['гвозди', 'nailgun'],
  'ammo.grenadelauncher.he': ['граната подствольник', '40мм осколочная', '40mm he'],
  'ammo.grenadelauncher.smoke': ['дымовая граната подствольник'],
  'ammo.grenadelauncher.buckshot': ['картечь подствольник'],
  // — Ресурсы —
  wood: ['дерево', 'дрова'],
  stones: ['камень', 'камни'],
  'metal.fragments': ['металл', 'фраги', 'фрагменты металла'],
  'metal.refined': ['hqm', 'мвк', 'качок', 'мк', 'качественный металл', 'металл вк', 'металл высокого качества'],
  sulfur: ['сера', 'серу', 'серка'],
  charcoal: ['уголь', 'чаркол'],
  'sulfur.ore': ['серная руда'],
  'metal.ore': ['металлическая руда'],
  'hq.metal.ore': ['руда hqm', 'руда качка', 'руда мвк'],
  'crude.oil': ['нефть', 'сырая нефть', 'crude'],
  lowgradefuel: ['топливо', 'тнк', 'нг', 'низкосортное топливо', 'солярка', 'lowgrade'],
  cloth: ['ткань'],
  leather: ['кожа'],
  scrap: ['скрап', 'лом', 'металлолом'],
  'fat.animal': ['жир', 'животный жир'],
  'bone.fragments': ['кости', 'костяные фрагменты'],
  water: ['вода'],
  'water.salt': ['солёная вода', 'соленая вода'],
  diesel_barrel: ['дизель', 'diesel'],
  'can.tuna': ['тунец', 'банка тунца'],
  'can.beans': ['бобы', 'фасоль', 'банка бобов'],
  // — Компоненты —
  gears: ['шестерни', 'шестеренки', 'gears'],
  metalpipe: ['трубы', 'металлические трубы', 'pipe'],
  metalblade: ['лезвия', 'metal blade'],
  metalspring: ['пружина', 'пружины', 'spring'],
  roadsigns: ['дорожные знаки', 'знаки'],
  rope: ['верёвка', 'веревка'],
  sewingkit: ['швейный набор', 'нитки'],
  sheetmetal: ['листовой металл', 'лист металла'],
  tarp: ['брезент'],
  techparts: ['тех мусор', 'техмусор', 'тех. мусор', 'tech trash', 'компы', 'компоненты', 'микросхемы', 'микросхема'],
  propanetank: ['пропан', 'газовый баллон'],
  riflebody: ['корпус винтовки'],
  smgbody: ['корпус пп'],
  semibody: ['корпус полуавто'],
  fuse: ['предохранитель', 'фьюз', 'фуз'],
  sticks: ['палки'],
  glue: ['клей'],
  ducttape: ['скотч', 'лента'],
  // — Инструменты —
  hatchet: ['топор'],
  pickaxe: ['кирка', 'железная кирка'],
  'axe.salvaged': ['самодельный топор', 'топор самодел'],
  'icepick.salvaged': ['ледоруб'],
  jackhammer: ['отбойный молоток', 'отбойник', 'бур', 'назар'],
  chainsaw: ['бензопила', 'пила'],
  hammer: ['молоток', 'кия', 'киянка'],
  'hammer.salvaged': ['самодельный молот'],
  'stone.pickaxe': ['каменная кирка'],
  stonehatchet: ['каменный топор'],
  torch: ['факел'],
  sickle: ['серп'],
  'fishingrod.handmade': ['удочка'],
  // — Медицина —
  'syringe.medical': ['шприц', 'медшприц', 'медицинский шприц'],
  largemedkit: ['медкит', 'аптечка', 'большая аптечка'],
  bandage: ['бинт'],
  antiradpills: ['таблетки от радиации', 'антирад таблетки'],
  // — Оружие (топ ганы и не только) —
  'rifle.ak': ['ак', 'калаш', 'ak', 'ak47', 'акм', 'ак47', 'автомат калашникова'],
  'rifle.bolt': ['болт', 'болтовка', 'снайперка', 'болтовая винтовка'],
  'rifle.lr300': ['lr300', 'лр300', 'лрка', 'лр'],
  'rifle.semiauto': ['берданка', 'берда', 'сар', 'sar', 'полуавтомат винтовка'],
  'rifle.l96': ['l96', 'л96', 'элка', 'элька'],
  'rifle.m39': ['m39', 'м39'],
  'smg.2': ['смг', 'сёмга', 'семга', 'кастомный пп', 'custom smg', 'кастом'],
  'smg.thompson': ['томпсон', 'томик', 'thompson'],
  'smg.mp5': ['mp5', 'мп5', 'мка', 'мппятка', 'пятка'],
  'pistol.semiauto': ['пешка', 'пистолет'],
  'pistol.python': ['питон', 'python'],
  'pistol.revolver': ['револьвер'],
  'pistol.m92': ['m92', 'м92', 'беретта'],
  'pistol.eoka': ['еока', 'йока', 'ёка', 'еошка'],
  'pistol.nailgun': ['гвоздомёт'],
  'shotgun.pump': ['помповик', 'помпа', 'помп'],
  'shotgun.double': ['двустволка', 'двушка', 'двойной обрез'],
  'shotgun.waterpipe': ['самопал', 'пайпа', 'пайп', 'обрез'],
  'shotgun.spas12': ['spas12', 'спас'],
  'lmg.m249': ['m249', 'м249', 'пулемёт', 'пулик'],
  hmlmg: ['самодельный пулемёт', 'hmlmg'],
  multiplegrenadelauncher: ['мгл', 'гранатомёт', 'm32'],
  'rocket.launcher': ['рпг', 'ракетница'],
  'bow.hunting': ['лук', 'охотничий лук'],
  'bow.compound': ['блочный лук', 'блочка', 'compound bow'],
  crossbow: ['арбалет'],
  // — Снаряжение —
  hazmatsuit: ['антирад', 'хазмат', 'антирадиационный костюм', 'химза'],
  // — Постройки / девайсы (часто торгуют) —
  'wall.frame.garagedoor': ['гаражка', 'гаражная дверь', 'гараж дверь'],
  'wall.external.high.stone': ['каменный забор', 'забор'],
  'wall.external.high': ['деревянный забор'],
  'door.hinged.toptier': ['бронедверь', 'бронированная дверь'],
  'door.hinged.metal': ['металлическая дверь', 'железная дверь'],
  'floor.ladder.hatch': ['люк'],
  'box.wooden.large': ['ящик', 'большой ящик', 'сундук'],
  'cupboard.tool': ['шкаф', 'тс', 'шкаф инструментов'],
  sleepingbag: ['спальник', 'спальный мешок'],
  furnace: ['печь'],
  workbench1: ['верстак 1', 'верстак1', 'wb1'],
  workbench2: ['верстак 2', 'верстак2', 'wb2'],
  workbench3: ['верстак 3', 'верстак3', 'wb3'],
  autoturret: ['турель'],
  guntrap: ['капкан', 'дробовик-ловушка'],
  samsite: ['самсайт', 'сам', 'sam site'],
  'generator.wind.scrap': ['ветряк', 'ветрогенератор', 'турбина'],
};

// Currency tokens recognised at the END of a price query ("ракета сера").
// alias -> shortName (resolved to an item id by items.js). Anything else is
// treated as part of the item name, so a normal "/price ракета" still works.
export const CURRENCY_ALIASES = {
  scrap: 'scrap', скрап: 'scrap', лом: 'scrap',
  сера: 'sulfur', серу: 'sulfur', sulfur: 'sulfur', серка: 'sulfur',
  дерево: 'wood', wood: 'wood', дрова: 'wood',
  камень: 'stones', камни: 'stones', stone: 'stones', stones: 'stones',
  металл: 'metal.fragments', metal: 'metal.fragments', фраги: 'metal.fragments',
  hqm: 'metal.refined', hq: 'metal.refined', качок: 'metal.refined', мвк: 'metal.refined',
  нг: 'lowgradefuel', тнк: 'lowgradefuel', топливо: 'lowgradefuel', lowgrade: 'lowgradefuel', солярка: 'lowgradefuel',
  ткань: 'cloth', cloth: 'cloth',
};
